### PR TITLE
Don't generate passwords so that direct ssh access is possible

### PR DESCRIPTION
**Pull request by bodymindarts**
We are already generating a password for ssh access via safe gen.

### CODE REVIEW

**Comment by geofffranks** [comment]
That was set as a best practice to have randomized, secure by default passwords. You can still bosh ssh and get in without passwords and use passwordless sudo.

**Comment by bodymindarts** [comment]
We've had difficulty using bosh ssh because we have not been able to add the routes as is possible when using bosh-lite locally

**Comment by geofffranks** [comment]
There're two optiona for that - install bosh cli on the bosh-lite, and ssh into it, target localhost, and bosh-ssh, or these options in theBOSH cli (might be easier to make use of after the issue for genesis bosh flags/config gets implemented):

```
--gateway_host HOST                                                     Gateway host
--gateway_user USER                                                     Gateway user
--gateway_identity_file FILE                                            Gateway identity file
```

**Comment by jhunt** [comment]
Can't this be handled on a per-site basis via overrides?

**Comment by jhunt** [comment]
@bodymindarts / @geofffranks any resolution on this?

**Comment by geofffranks** [comment]
Also there's a third option now - gaol-basher via toolbelt-boshrelease

**Pull request closed without merging**
